import "@/styles/globals.css";

import { type Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const jetbrain_mono = JetBrains_Mono({
  variable: "--font-mono-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${jetbrain_mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
